version: '3.3'

services:

  db:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: 'crawler'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'user'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Puerto expuesto> : < MySQL Puerto corriendo dentro del contenedor>
      - '3306:3306'
    expose:
      # Abre el puerto 3306 al contenedor
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  crawler:
    depends_on:
      - db
    build:
      context: ./dockerfile_dir
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

# Names our volume
volumes:
  my-db: