version: '3.3'

services:

  crawler:
    depends_on:
      - db
    build:
      context: ./dockerfile_dir
      dockerfile: Dockerfile
    # Para que se ejecute de modo interactivo
    stdin_open: true
    tty: true

    expose:
      - '3306'

  db:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: 'crawler'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    ports:
      # <Puerto expuesto> : < MySQL Puerto corriendo dentro del contenedor>
      - '3306:3306'
